<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Activation email' => '',
    'This email has already been taken.' => '',
    'Your account has been successfully activated.' => '',
    'Your account has been successfully created. Check your email for further instructions.' => '',
    'Your activation link: {url}' => '',
    'About' => '',
    'Account Settings' => '',
    'Articles' => '',
    'Attachments' => '',
    'Backend' => '',
    'Body' => '',
    'Check your email for further instructions.' => '',
    'Confirm Password' => '',
    'Contact' => '',
    'E-mail' => '',
    'Email' => 'Email',
    'Error while oauth process.' => '',
    'Female' => '',
    'Home' => '',
    'If you forgot your password you can reset it <a href="{link}">here</a>' => ' Nếu bạn quên mật khẩu hãy reset nó tại <a href="{link}">đây</a>',
    'Incorrect username or password.' => 'Tài khoản và mật khẩu chưa chính xác',
    'Language' => 'Ngôn ngữ',
    'Log in with' => '',
    'Login' => '',
    'Logout' => '',
    'Male' => '',
    'Name' => '',
    'Need an account? Sign up.' => '',
    'New password was saved.' => 'Mật khẩu mới đã được lưu thành công',
    'Page not found' => 'Không tìm thấy trang',
    'Password' => 'Mật khẩu',
    'Password reset for {name}' => 'Thiết lập lại mật khẩu cho {name}',
    'Profile settings' => 'Tùy chỉnh hồ sơ',
    'Remember Me' => 'Nhớ tôi',
    'Request password reset' => 'Thiết lập lại mật khẩu',
    'Reset password' => '',
    'Settings' => '',
    'Sign up with' => '',
    'Signup' => '',
    'Sorry, we are unable to reset password for email provided.' => 'Hệ thống không thể thiết lập mật khẩu cho email đã cung cấp.',
    'Subject' => 'Tiêu đề',
    'Submit' => 'Gửi',
    'Thank you for contacting us. We will respond to you as soon as possible.' => '',
    'There was an error sending email.' => '',
    'This email address has already been taken.' => '',
    'This username has already been taken.' => '',
    'Update' => '',
    'User Settings' => '',
    'Username' => '',
    'Username or email' => '',
    'Verification Code' => '',
    'We already have a user with email {email}' => '',
    'Welcome to {app-name}. Email with your login information was sent to your email.' => '',
    'Your account has been successfully saved' => '',
    '{app-name} | Your login information' => '{app-name} | ',
];
